#!/bin/bash
while true
do
	echo "Who do you want advice from? "
	cat << options
bunny
tux
daemon
kitty
vader-koala
options
echo
read -p "Make your choice, please: " option
if [ "$option" = "quit" ]
 then 
 break
 else
 fortune | cowsay -f $option
fi
done
